package controller;

public enum Request {
    ADD_TO_CART,
    GET_ALL_ITEMS,  // skickar items
    GET_ALL_CATEGORIES,
    GET_ALL_COLORS,
    GET_SIZES_BY_PRODUCT_TYPE,
    GET_ALL_PRODUCT_TYPES,
    GET_CUSTOMER_BY_ID,
    GET_ORDER_BY_CUSTOMER_ID,
    LOGIN_CUSTOMER,
    REPORT_TOP_TEN_PRODUCTS,
    REPORT_CITY_RANKING,
    REPORT_CUSTOMER_ORDER_RATE,
    REPORT_CUSTOMER_SPENDING
}
